### ISSUE TITLE
Tutorial Install and use

### ISSUE THREAD

**Issue by AntonioAlgaida** [ajackal/cherry-wasp#2]
How can I use the sniffer?
I'm using on a rpi 3B+
I've tried to install it, but when I try to execute corescanner.py with:
`python corescanner.py`

it says:
```
Traceback (most recent call last):
  File "corescanner.py", line 6, in <module>
    from cherrywasp import accesspoint
ImportError: No module named cherrywasp
```

Thanks

**Comment by ajackal** [comment]
It was an issue with the way I wrote the import. Would work in some environments and not others. I believe I have fixed it. Try again and let me know!

**Comment by AntonioAlgaida** [comment]
Now works nice! Thanks
